// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	PersistUser(ctx context.Context, arg PersistUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
