app:
  name: ser
  http_port: 8090
  env: stage

ddb:
  region: ap-south-1

metric:
  enabled: true
  prefix: "ser"
  reporting_interval_ms: 1000
  enable_prometheus: true
  enable_statsd: false
  statsd:
    address: 127.0.0.1:1234
    flush_interval_ms: 10
    flush_bytes: 1440
  tracing:
    enabled: true
    dd:
      enabled: true
      host: localhost
      port: 8126
      env: stage

server_config:
  servers:
    jsonplaceholder:
      host: jsonplaceholder.typicode.com
      port: 443
      https: true
      connect_timeout: 10000
      connection_request_timeout: 10000
    testServer:
      host: localhost
      port: 9123
  apis:
    getPost:
      method: GET
      path: /todos/{id}
      server: jsonplaceholder
      timeout: 10000
      acceptable_codes: 200,201
      concurrency: 1000
      queue_size: 1000
    delay_timeout_10:
      path: /delay
      server: testServer
      timeout: 10
      concurrency: 3

messaging_config:
  enabled: false
  producers:
    some-topic:
      type: kafka
      topic: some-topic
      endpoint: localhost:9092
      session.timeout.ms: 1000
      message_timeout_ms: 1000
      properties:
        acks: all